# Generated by Django 5.2.1 on 2026-01-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_oerresource_content_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oerresource',
            name='coverage_notes',
            field=models.TextField(blank=True, help_text='Coverage statement or notes from KBART'),
        ),
        migrations.AddField(
            model_name='oerresource',
            name='date_first_issue_online',
            field=models.CharField(blank=True, help_text='First available online date (YYYY-MM-DD)', max_length=10),
        ),
        migrations.AddField(
            model_name='oerresource',
            name='date_last_issue_online',
            field=models.CharField(blank=True, help_text='Last available online date (YYYY-MM-DD)', max_length=10),
        ),
        migrations.AddField(
            model_name='oerresource',
            name='embargo_info',
            field=models.CharField(blank=True, help_text='Embargo or access restriction info', max_length=200),
        ),
        migrations.AddField(
            model_name='oerresource',
            name='num_first_issue_online',
            field=models.CharField(blank=True, help_text='First issue number available', max_length=50),
        ),
        migrations.AddField(
            model_name='oerresource',
            name='num_first_vol_online',
            field=models.CharField(blank=True, help_text='First volume number available', max_length=50),
        ),
        migrations.AddField(
            model_name='oerresource',
            name='publication_year',
            field=models.CharField(blank=True, db_index=True, help_text='Year of publication (YYYY format)', max_length=4),
        ),
    ]
