# Generated by Django 5.2.1 on 2026-01-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_oerresource_coverage_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oerresource',
            name='ai_pedagogy_scores',
            field=models.JSONField(blank=True, default=dict, help_text='AI pedagogical assessment scores (clarity, objectives, practice, etc.)'),
        ),
        migrations.AddField(
            model_name='oerresource',
            name='ai_review_confidence',
            field=models.FloatField(blank=True, help_text='Confidence in AI review 0-1', null=True),
        ),
        migrations.AddField(
            model_name='oerresource',
            name='ai_review_summary',
            field=models.TextField(blank=True, help_text='AI-generated teaching utility summary'),
        ),
        migrations.AddField(
            model_name='oerresource',
            name='metadata_quality_score',
            field=models.FloatField(default=0.0, help_text='Metadata completeness 0-1 (factual, not subjective quality)'),
        ),
        migrations.AddField(
            model_name='oerresource',
            name='readiness_for_review',
            field=models.BooleanField(default=False, help_text='Has sufficient metadata for AI/human quality review (≥70% complete)'),
        ),
        migrations.AddField(
            model_name='oerresource',
            name='trust_signals',
            field=models.JSONField(blank=True, default=dict, help_text='Factual trust indicators: from_curated_collection, open_license, updated_recently, etc.'),
        ),
        migrations.AlterField(
            model_name='oerresource',
            name='overall_quality_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='Legacy quality score (0-5 scale) - being phased out'),
        ),
    ]
