# Generated by Django 5.2.1 on 2026-01-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_oerresource_ai_pedagogy_scores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oerresource',
            name='description_last_enriched_at',
            field=models.DateTimeField(blank=True, help_text='When description was last enriched from resource URL', null=True),
        ),
    ]
