# Generated by Django 5.2.1 on 2026-01-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_oerresource_description_last_enriched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='oerresource',
            name='date_first_published',
            field=models.DateField(blank=True, help_text='Original publication date, if known.', null=True),
        ),
    ]
